### ISSUE TITLE
Doesn't work with older Gnome Shell versions

### ISSUE THREAD

**Issue by fawtytoo** [sustmi/gnome-shell-extension-workspace-switcher-popup-thumbnails#4]
This extension would be useful to me but I'm still using Gnome 2.22. Any chance of adding that version?

**Comment by sustmi** [comment]
Hi @phenest . I guess you meant GNOME Shell v3.22 (not 2.22).
I added the compatibility for v3.22 in a66d55fa017eeb8546adc23d29cb1d44acdfe29b . Can you test it?
It will be also released as `v2` after review process on https://extensions.gnome.org .

**Comment by sustmi** [comment]
Hi @phenest . I guess you meant GNOME Shell v3.22 (not 2.22).
I added the compatibility for v3.22 in a66d55fa017eeb8546adc23d29cb1d44acdfe29b . Can you test it?
It will be also released as `v2` after review process on https://extensions.gnome.org .

**Comment by sustmi** [comment]
Closing the issue as I believe that it is fixed.
